name: Start Kaggle Notebook

on:
  schedule:
    - cron: '*/20 * * * *'  # هر ۲۰ دقیقه یک بار اجرا میشه
  workflow_dispatch:        # امکان اجرای دستی

jobs:
  start-kaggle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Run Kaggle starter script
      run: python start_kaggle.py
